# Generated by Django 5.1 on 2024-12-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_descripcion_customuser_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comuna',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
    ]
