# Generated by Django 5.1 on 2024-12-16 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_purchasehistory'),
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gusto_producto', models.CharField(choices=[('muy_bueno', 'Muy Bueno'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('muy_malo', 'Muy Malo')], default='regular', max_length=10)),
                ('informacion_producto', models.CharField(choices=[('muy_bueno', 'Muy Bueno'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('muy_malo', 'Muy Malo')], default='regular', max_length=10)),
                ('experiencia_pagina', models.CharField(choices=[('muy_bueno', 'Muy Bueno'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('muy_malo', 'Muy Malo')], default='regular', max_length=10)),
                ('comentarios_adicionales', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
