# Generated by Django 5.1 on 2024-12-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_vendido_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendido',
            field=models.BooleanField(default=False, verbose_name='Estado Vendido'),
        ),
    ]
